# Generated by Django 4.1.3 on 2022-11-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallindrome',
            name='p_or_not',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
